version: '3.6'

services:
  node-server:
    build:
      context: .
      args:
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 3001:${PORT}
      - '9229:9229'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    # command: 'nodemon --inspect=0.0.0.0:9229 -L --nolazy src/server.ts'
