version: '3.6'

services:
  node-server:
    build:
      context: .
      args:
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 3000:${PORT:-3000}
    volumes:
      - ./src:/app/src
    env_file:
      - .env
